-- Delete Rows in Tables !!! Make sure to delete id 62> from mail_followers manually !!!
DELETE FROM "public"."stock_move";
DELETE FROM "public"."stock_move_operation_link";
DELETE FROM "public"."stock_quant";
DELETE FROM "public"."stock_quant_move_rel";
DELETE FROM "public"."stock_pack_operation";
DELETE FROM "public"."stock_picking";
DELETE FROM "public"."sale_order_line";
DELETE FROM "public"."sale_order_line_invoice_rel";
DELETE FROM "public"."sale_order";
DELETE FROM "public"."payment_transaction";
DELETE FROM "public"."procurement_order";
DELETE FROM "public"."procurement_group";
DELETE FROM "public"."crm_lead";
DELETE FROM "public"."account_payment";
DELETE FROM "public"."account_partial_reconcile";
DELETE FROM "public"."account_invoice_tax";
DELETE FROM "public"."account_invoice_payment_rel";
DELETE FROM "public"."account_invoice";
DELETE FROM "public"."account_invoice_line_tax";
DELETE FROM "public"."account_invoice_line";
DELETE FROM "public"."account_invoice_account_move_line_rel";
DELETE FROM "public"."account_move_line_account_tax_rel";
DELETE FROM "public"."account_move_line";
DELETE FROM "public"."account_move";
DELETE FROM "public"."account_bank_statement_line";
DELETE FROM "public"."account_cashbox_line";
DELETE FROM "public"."account_bank_statement_cashbox";
DELETE FROM "public"."account_bank_statement";
DELETE FROM "public"."account_full_reconcile";
DELETE FROM "public"."account_tax_pos_order_line_rel";
DELETE FROM "public"."account_tax_purchase_order_line_rel";
DELETE FROM "public"."account_tax_sale_order_line_rel";
DELETE FROM "public"."account_tax_sale_advance_payment_inv_rel";
DELETE FROM "public"."pos_order_line";
DELETE FROM "public"."pos_order";
DELETE FROM "public"."pos_session";
DELETE FROM "public"."pos_open_statement";
DELETE FROM "public"."cash_box_in";
DELETE FROM "public"."cash_box_out";
DELETE FROM "public"."account_cashbox_line";
DELETE FROM "public"."mail_message_mail_channel_rel";
DELETE FROM "public"."mail_tracking_value";
DELETE FROM "public"."message_attachment_rel";
DELETE FROM "public"."mail_message";

-- Reset Key Sequence
SELECT setval(pg_get_serial_sequence('stock_move', 'id'), coalesce(max(id),0) + 1, false) FROM stock_move;
SELECT setval(pg_get_serial_sequence('stock_move_operation_link', 'id'), coalesce(max(id),0) + 1, false) FROM stock_move_operation_link;
SELECT setval(pg_get_serial_sequence('stock_quant', 'id'), coalesce(max(id),0) + 1, false) FROM stock_quant;
SELECT setval(pg_get_serial_sequence('stock_pack_operation', 'id'), coalesce(max(id),0) + 1, false) FROM stock_pack_operation;
SELECT setval(pg_get_serial_sequence('stock_picking', 'id'), coalesce(max(id),0) + 1, false) FROM stock_picking;
SELECT setval(pg_get_serial_sequence('sale_order_line', 'id'), coalesce(max(id),0) + 1, false) FROM sale_order_line;
SELECT setval(pg_get_serial_sequence('sale_order', 'id'), coalesce(max(id),0) + 1, false) FROM sale_order;
SELECT setval(pg_get_serial_sequence('payment_transaction', 'id'), coalesce(max(id),0) + 1, false) FROM payment_transaction;
SELECT setval(pg_get_serial_sequence('procurement_group', 'id'), coalesce(max(id),0) + 1, false) FROM procurement_group;
SELECT setval(pg_get_serial_sequence('procurement_order', 'id'), coalesce(max(id),0) + 1, false) FROM procurement_order;
SELECT setval(pg_get_serial_sequence('crm_lead', 'id'), coalesce(max(id),0) + 1, false) FROM crm_lead;
SELECT setval(pg_get_serial_sequence('account_payment', 'id'), coalesce(max(id),0) + 1, false) FROM account_payment;
SELECT setval(pg_get_serial_sequence('account_partial_reconcile', 'id'), coalesce(max(id),0) + 1, false) FROM account_partial_reconcile;
SELECT setval(pg_get_serial_sequence('account_invoice_tax', 'id'), coalesce(max(id),0) + 1, false) FROM account_invoice_tax;
SELECT setval(pg_get_serial_sequence('account_invoice', 'id'), coalesce(max(id),0) + 1, false) FROM account_invoice;
SELECT setval(pg_get_serial_sequence('account_invoice_line', 'id'), coalesce(max(id),0) + 1, false) FROM account_invoice_line;
SELECT setval(pg_get_serial_sequence('account_move_line', 'id'), coalesce(max(id),0) + 1, false) FROM account_move_line;
SELECT setval(pg_get_serial_sequence('account_move', 'id'), coalesce(max(id),0) + 1, false) FROM account_move;
SELECT setval(pg_get_serial_sequence('account_bank_statement_line', 'id'), coalesce(max(id),0) + 1, false) FROM account_bank_statement_line;
SELECT setval(pg_get_serial_sequence('account_cashbox_line', 'id'), coalesce(max(id),0) + 1, false) FROM account_cashbox_line;
SELECT setval(pg_get_serial_sequence('account_bank_statement_cashbox', 'id'), coalesce(max(id),0) + 1, false) FROM account_bank_statement_cashbox;
SELECT setval(pg_get_serial_sequence('account_bank_statement', 'id'), coalesce(max(id),0) + 1, false) FROM account_bank_statement;
SELECT setval(pg_get_serial_sequence('account_full_reconcile', 'id'), coalesce(max(id),0) + 1, false) FROM account_full_reconcile;
SELECT setval(pg_get_serial_sequence('pos_order_line', 'id'), coalesce(max(id),0) + 1, false) FROM pos_order_line;
SELECT setval(pg_get_serial_sequence('pos_order', 'id'), coalesce(max(id),0) + 1, false) FROM pos_order;
SELECT setval(pg_get_serial_sequence('pos_session', 'id'), coalesce(max(id),0) + 1, false) FROM pos_session;
SELECT setval(pg_get_serial_sequence('pos_open_statement', 'id'), coalesce(max(id),0) + 1, false) FROM pos_open_statement;
SELECT setval(pg_get_serial_sequence('cash_box_in', 'id'), coalesce(max(id),0) + 1, false) FROM cash_box_in;
SELECT setval(pg_get_serial_sequence('cash_box_out', 'id'), coalesce(max(id),0) + 1, false) FROM cash_box_out;
SELECT setval(pg_get_serial_sequence('account_cashbox_line', 'id'), coalesce(max(id),0) + 1, false) FROM account_cashbox_line;
SELECT setval(pg_get_serial_sequence('mail_followers', 'id'), coalesce(max(id),0) + 1, false) FROM mail_followers;
SELECT setval(pg_get_serial_sequence('mail_tracking_value', 'id'), coalesce(max(id),0) + 1, false) FROM mail_tracking_value;
SELECT setval(pg_get_serial_sequence('mail_message', 'id'), coalesce(max(id),0) + 1, false) FROM mail_message;

